# Generated by Django 4.1 on 2022-09-10 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrollador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('legajo', models.IntegerField()),
                ('puesto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dicty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_grupo', models.IntegerField()),
                ('tabla', models.CharField(max_length=30)),
                ('desarrollador', models.IntegerField()),
                ('frecuencia_act', models.CharField(max_length=30)),
                ('area_solicitud', models.CharField(max_length=30)),
                ('herramienta', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(db_index=True, max_length=240)),
                ('descripcion', models.CharField(db_index=True, max_length=240)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDictClaro.dicty')),
            ],
        ),
    ]
