# Generated by Django 4.1 on 2022-09-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDictClaro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla',
            name='container',
            field=models.CharField(max_length=50),
        ),
    ]
