# Generated by Django 4.1 on 2022-09-18 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDictClaro', '0002_alter_tabla_container'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabla',
            old_name='container',
            new_name='nombre',
        ),
    ]
